# Generated by Django 5.2.17 on 2026-10-03 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('grade', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('其他', '其他')], max_length=10, verbose_name='当前年级')),
                ('curriculum', models.CharField(blank=True, max_length=30, verbose_name='教材')),
                ('chapter', models.CharField(blank=True, max_length=100, verbose_name='章节')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='主要内容')),
                ('usual_raw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='平时裸分')),
                ('usual_scaled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='平时赋分')),
                ('target_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='目标分（赋分）')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='期望学校')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['archived', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='考试日期')),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='裸分')),
                ('scaled_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='赋分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='workspace.student')),
            ],
            options={
                'ordering': ['-date', '-created_at', '-pk'],
            },
        ),
    ]
