# Generated by Django 5.2.17 on 2026-10-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('rule', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='课程日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('scheduled', '待上课'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=12)),
                ('next_goal', models.TextField(blank=True, max_length=2000, verbose_name='下次课目标（内部备课）')),
                ('progress_snapshot', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='workspace.courseseries')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='workspace.student')),
            ],
            options={
                'ordering': ['date', 'start_time', 'pk'],
                'indexes': [models.Index(fields=['date', 'status'], name='workspace_l_date_af5d91_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='lesson_positive_duration')],
            },
        ),
    ]
