# Generated by Django 5.2.17 on 2026-10-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_courseseries_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_template', models.TextField(default='一、上课内容\n1.……\n二、学生情况\n1.……\n三、课后作业\n……', max_length=6000, verbose_name='反馈正文模板')),
                ('instructions', models.TextField(default='语言自然、具体，保留老师语气。整理口语笔记，保留正确率和未掌握的问题，不用套话补充内容。', max_length=6000, verbose_name='生成要求')),
                ('model', models.CharField(default='qwen3.7-flash', max_length=100, verbose_name='模型名称')),
            ],
        ),
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='workspace.lesson')),
            ],
        ),
    ]
