# Generated by Django 5.2.17 on 2026-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_feedbacksettings_lessonfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksettings',
            name='vision_model',
            field=models.CharField(default='qwen3-vl-flash', max_length=100, verbose_name='图片课表识别模型'),
        ),
    ]
